#!/bin/bash

# On construit l'URL pour l'API YouTube :
temp=$(echo "$*" | sed -e "s/ /+/g")
surl="https://gdata.youtube.com/feeds/api/videos?q=$temp&max-results=1"

# On récupère l'URL de la première vidéo correspondant au termes recherchés :
wget -q --no-check-certificate -O .youtube "$surl"
xmlstarlet fo .youtube > .youtube.nice
vurl=$(cat .youtube.nice | grep "<link rel=\"alternate\"" | grep gdata | cut -d "\"" -f 6)

# Afficher les commandes clavier :
echo "p: pause"
echo "m: mute"
echo "/, *: volume + et -"
echo "gauche et droite: +/- 10secondes"

# Playback time !
cookiefile="/tmp/cookies-$( date +%s.%N ).txt";
url=$( youtube-dl --cookies $cookiefile -g "$vurl" );
mplayer -really-quiet -cookies -cookies-file $cookiefile -vo null $url;
rm -f $cookiefile
rm -f .youtube
rm -f .youtube.nice

